zotero:
  user_id: ${oc.env:ZOTERO_ID}
  api_key: ${oc.env:ZOTERO_KEY}
  include_path: null
  import_enabled: true
  import_score_threshold: 5.0
  import_collections:
    RF-Circuit: 34AQUCS9
    Passive-Device: 3KU6BGFU
    Surrogate-Model: 9A72IDH4
    EDA: 8WTREBUB
    AI-Circuit-Design: 5PXXHKIZ # Or set a list of glob patterns, e.g. ["2026/survey/**","2026/reading-group/**"]

email:
  sender: ${oc.env:SENDER}
  receiver: ${oc.env:RECEIVER}
  smtp_server: smtp.exmail.qq.com
  smtp_port: 465
  sender_password: ${oc.env:SENDER_PASSWORD}

llm:
  api:
    key: ${oc.env:OPENAI_API_KEY}
    base_url: ${oc.env:OPENAI_API_BASE}
  generation_kwargs:
    model: ${oc.env:OPENAI_MODEL,gpt-4o-mini}

source:
  arxiv:
    category: ["eess.SP","physics.app-ph","physics.ins-det","cs.AR","cs.CE","cs.ET","cs.LG","cs.AI","cs.NE"]
    include_cross_list: true

executor:
  debug: ${oc.env:DEBUG,null}
  source: ['arxiv']
